[global]
exclude = [         
    "*LICENSE*",
    "*/.github/*",
    "*/tests/*",
    "*/src/*",
]

[style]
headings="consistent"
unordered_lists="consistent"
num_spaces_after_list_marker=1
bold="consistent"

[fmt]
check=false
show_diff=false

[link_checker]
ignore_wildcards=["**gffffffffffoooooogel**", "/**.rs"]
timeout=10
max_retries=1

[linter]
allowed_html_tags=["img"]

[review]                          
no_suggestions=false
creativity=10

[compose]
creativity=80

[spelling]
words_whitelist=[]
